/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // --- Munim brand + WhatsApp (dashboard + simulator) ---
        brand: {
          50: "#ecfdf5", 100: "#d1fae5", 400: "#34d399", 500: "#10b981",
          600: "#0d9488", 700: "#0f766e", 800: "#115e59", 900: "#0f3d3e", 950: "#0a2e2e",
        },
        wa: { bg: "#0b141a", panel: "#111b21", bubble: "#005c4b", inbound: "#202c33" },
        // --- Material design tokens (landing / auth / onboarding pages) ---
        "surface-tint": "#236a53",
        "surface-container-highest": "#d9e3f9",
        "surface-container": "#e7eeff",
        "outline-variant": "#bfc9c2",
        secondary: "#006e2f",
        "on-secondary": "#ffffff",
        "inverse-surface": "#273141",
        tertiary: "#363b39",
        "surface-bright": "#f9f9ff",
        primary: "#004331",
        surface: "#f9f9ff",
        "primary-fixed-dim": "#8fd5b8",
        outline: "#6f7974",
        "on-surface-variant": "#3f4944",
        "secondary-fixed-dim": "#4ae176",
        "surface-container-high": "#dee8ff",
        "on-primary-container": "#8dd2b6",
        "surface-container-low": "#f0f3ff",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "primary-fixed": "#abf1d4",
        "tertiary-container": "#4d5250",
        "error-container": "#ffdad6",
        "primary-container": "#0f5c46",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d9e3f9",
        "secondary-fixed": "#6bff8f",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#121c2c",
        background: "#F5FAF7",
        "surface-dim": "#d0daf0",
        "secondary-container": "#6bff8f",
        "munim-green": "#0F5C46",
        "signal-green": "#4ae176",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "numeral-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        "card-padding": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "section-gap": "64px",
        "touch-target-min": "48px",
      },
      boxShadow: {
        card: "0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)",
        "soft-depth": "0px 4px 20px rgba(15, 92, 70, 0.08)",
        "float-depth": "0px 8px 32px rgba(15, 92, 70, 0.12)",
      },
    },
  },
  plugins: [],
};
