/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#236a53",
        "on-tertiary-fixed": "#171d1b",
        "surface-container-highest": "#d9e3f9",
        "surface-container": "#e7eeff",
        "outline-variant": "#bfc9c2",
        secondary: "#006e2f",
        "on-secondary": "#ffffff",
        "inverse-surface": "#273141",
        tertiary: "#363b39",
        "inverse-on-surface": "#ebf1ff",
        "on-tertiary-container": "#c0c5c2",
        "surface-bright": "#f9f9ff",
        primary: "#004331",
        surface: "#f9f9ff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#8fd5b8",
        outline: "#6f7974",
        "on-primary-fixed-variant": "#00513c",
        "on-surface-variant": "#3f4944",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#4ae176",
        "tertiary-fixed": "#dee4e1",
        "surface-container-high": "#dee8ff",
        "on-secondary-fixed": "#002109",
        "on-primary-container": "#8dd2b6",
        "surface-container-low": "#f0f3ff",
        "on-primary": "#ffffff",
        "inverse-primary": "#8fd5b8",
        error: "#ba1a1a",
        "on-secondary-container": "#007432",
        "primary-fixed": "#abf1d4",
        "tertiary-container": "#4d5250",
        "error-container": "#ffdad6",
        "on-background": "#121c2c",
        "tertiary-fixed-dim": "#c2c8c5",
        "primary-container": "#0f5c46",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#002116",
        "surface-variant": "#d9e3f9",
        "secondary-fixed": "#6bff8f",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#121c2c",
        background: "#F5FAF7",
        "surface-dim": "#d0daf0",
        "on-tertiary-fixed-variant": "#424846",
        "secondary-container": "#6bff8f",
        "on-secondary-fixed-variant": "#005321",
        "munim-green": "#0F5C46",
        "canvas-mint": "#F5FAF7",
        "signal-green": "#4ae176",
        coral: "#ba1a1a",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "numeral-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "numeral-md": ["18px", { lineHeight: "24px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "card-padding": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "section-gap": "64px",
        gutter: "16px",
        "touch-target-min": "48px",
        base: "8px",
      },
      boxShadow: {
        "soft-depth": "0px 4px 20px rgba(15, 92, 70, 0.08)",
        "float-depth": "0px 8px 32px rgba(15, 92, 70, 0.12)",
      },
    },
  },
  plugins: [],
};
